<a href="https://colab.research.google.com/github/Emmanuelkiptim/Digital-Marketing-Performance-Analysis/blob/main/Digital_Marketing_Performance_Analysis_Identifying_Profitable_Channels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The company has been investing in multiple marketing channels but lacks clarity on which campaigns are delivering value. Some campaigns may be consuming a large portion of the budget without generating sufficient conversions or revenue.

Without proper analysis, the marketing team risks continuing to invest in underperforming channels, leading to inefficient use of resources.

This project seeks to evaluate campaign performance and provide actionable recommendations on how to allocate the marketing budget effectively.

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### import and load the dataset

In [3]:
df=pd.read_csv("realistic_marketing_dataset.csv")
df.head()

         date       channel   spend  impressions  clicks  conversions  revenue
0  2024-01-01    Google Ads  230.52        12138     933          103  6066.65
1  2024-01-01  Facebook Ads  325.39         2936     117            5   219.81
2  2024-01-01     Instagram  214.28         2857     157            8   165.35
3  2024-01-01         Email  189.68         2323     245           37   796.06
4  2024-01-02    Google Ads  563.65         3731     285           35  1520.77

1. Data Eyeballing

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         2160 non-null   object
 1   channel      2160 non-null   object
 2   spend        2160 non-null   float64
 3   impressions  2160 non-null   int64
 4   clicks       2160 non-null   int64
 5   conversions  2160 non-null   int64
 6   revenue      2160 non-null   float64
dtypes: float64(2), int64(3), object(2)
memory usage: 118.3+ KB

In [5]:
df.isna().sum()

date           0
channel        0
spend          0
impressions    0
clicks         0
conversions    0
revenue        0
dtype: int64

In [8]:
df.describe()
df['channel'].unique()

array(['Google Ads', 'Facebook Ads', 'Instagram', 'Email'], dtype=object)

2. Data Cleaning.

In [10]:
df.dtypes

date            object
channel         object
spend          float64
impressions      int64
clicks           int64
conversions      int64
revenue        float64
dtype: object

In [14]:
## replace date data type
df['date']=pd.to_datetime(df['date'])
df

,date,channel,spend,impressions,clicks,conversions,revenue
0,2024-01-01,Google Ads,230.52,12138,933,103,6066.65
1,2024-01-01,Facebook Ads,325.39,2936,117,5,219.81
2,2024-01-01,Instagram,214.28,2857,157,8,165.35
3,2024-01-01,Email,189.68,2323,245,37,796.06
4,2024-01-02,Google Ads,563.65,3731,285,35,1520.77
...,...,...,...,...,...,...,...
2155,2025-06-22,Email,152.48,9496,802,94,3496.78
2156,2025-06-23,Google Ads,545.81,4536,262,24,1005.36
2157,2025-06-23,Facebook Ads,208.99,3165,82,7,198.85
2158,2025-06-23,Instagram,210.15,5386,264,8,132.71
2159,2025-06-23,Email,186.64,10175,1027,129,5697.50


### The campaign dataset contains of marketing campaign data from instagram, email, facebook and google ads.
### The columns are: date, channel, spend, impressions, clicks, conversions, revenue.
### The data was cleaned enough no missing values were found. I only had to change the date data type from object to datetime.

3. Feature Engineering and Metrics Calculation

In [26]:
df['Click Through Rate']=df['clicks']/df['impressions']
df['Return On Ad Spend']=df['revenue']/df['spend']
df['Conversion Rate']=df['conversions']/df['clicks']
df

,date,channel,spend,impressions,clicks,conversions,revenue,Click Through Rate,Return On Ad Spend,Conversion Rate
0,2024-01-01,Google Ads,230.52,12138,933,103,6066.65,0.076866,26.317239,0.110397
1,2024-01-01,Facebook Ads,325.39,2936,117,5,219.81,0.039850,0.675528,0.042735
2,2024-01-01,Instagram,214.28,2857,157,8,165.35,0.054953,0.771654,0.050955
3,2024-01-01,Email,189.68,2323,245,37,796.06,0.105467,4.196858,0.151020
4,2024-01-02,Google Ads,563.65,3731,285,35,1520.77,0.076387,2.698075,0.122807
...,...,...,...,...,...,...,...,...,...,...
2155,2025-06-22,Email,152.48,9496,802,94,3496.78,0.084457,22.932712,0.117207
2156,2025-06-23,Google Ads,545.81,4536,262,24,1005.36,0.057760,1.841960,0.091603
2157,2025-06-23,Facebook Ads,208.99,3165,82,7,198.85,0.025908,0.951481,0.085366
2158,2025-06-23,Instagram,210.15,5386,264,8,132.71,0.049016,0.631501,0.030303
2159,2025-06-23,Email,186.64,10175,1027,129,5697.50,0.100934,30.526682,0.125609

### Created new calculation metrics that would assist in the analyzing of the data
1. Click Through rate
2. Return on Ad Spend
3. Conversion Rate

#### 4. Explore the data

Channel Performance analysis

In [29]:
channel_summary= df.groupby('channel').agg (
    {
        'Return On Ad Spend': 'mean',
        'spend':'sum',
        'revenue':'sum',
        'clicks':'sum',
        'conversions':'sum',

    }
).sort_values(by='Return On Ad Spend', ascending=False)
channel_summary

              Return On Ad Spend      spend     revenue  clicks  conversions
channel
Email                  41.041047   68645.65  2397836.63  468550        67962
Google Ads              6.059614  220788.51  1191792.44  277696        31420
Instagram               4.282049  141350.27   514662.12  233563        13560
Facebook Ads            3.077562  180787.24   491157.87  183421        13211